In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing

In [2]:
housing = fetch_california_housing()

X = housing.data
y = housing.target

df = pd.DataFrame(X, columns=housing.feature_names)

df["Price"] = y

In [3]:
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [4]:
df.describe()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
count,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,3.870671,28.639486,5.429000,1.096675,1425.476744,3.070655,35.631861,-119.569704,2.068558
std,1.899822,12.585558,2.474173,0.473911,1132.462122,10.386050,2.135952,2.003532,1.153956
min,0.499900,1.000000,0.846154,0.333333,3.000000,0.692308,32.540000,-124.350000,0.149990
25%,2.563400,18.000000,4.440716,1.006079,787.000000,2.429741,33.930000,-121.800000,1.196000
50%,3.534800,29.000000,5.229129,1.048780,1166.000000,2.818116,34.260000,-118.490000,1.797000
75%,4.743250,37.000000,6.052381,1.099526,1725.000000,3.282261,37.710000,-118.010000,2.647250
max,15.000100,52.000000,141.909091,34.066667,35682.000000,1243.333333,41.950000,-114.310000,5.000010

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
 8   Price       20640 non-null  float64
dtypes: float64(9)
memory usage: 1.4 MB

In [7]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
Price         0
dtype: int64

In [8]:
X = df.drop("Price", axis=1)

y = df["Price"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [16]:
alphas = [
    0.0001,
    0.001,
    0.01,
    0.1,
    1
]

for alpha in alphas:

    model = Lasso(
        alpha=alpha,
        random_state=42
    )

    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    print(
        f"Alpha = {alpha:<7}  R² = {r2_score(y_test,pred):.4f}"
    )

Alpha = 0.0001   R² = 0.5759
Alpha = 0.001    R² = 0.5769
Alpha = 0.01     R² = 0.5816
Alpha = 0.1      R² = 0.4814
Alpha = 1        R² = -0.0002

In [11]:
from sklearn.linear_model import Lasso

model = Lasso(
    alpha=0.01,
    random_state=42
)

model.fit(X_train, y_train)

Lasso(alpha=0.01, random_state=42)

In [12]:
pred = model.predict(X_test)

In [13]:
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_test, pred)

mse = mean_squared_error(y_test, pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R² :", r2)

MAE : 0.5353261423609053
MSE : 0.5482548967938964
RMSE: 0.7404423656125414
R² : 0.5816154300698727

In [14]:
coef = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_
})

print(coef)

      Feature  Coefficient
0      MedInc     0.800957
1    HouseAge     0.127087
2    AveRooms    -0.162759
3   AveBedrms     0.206207
4  Population    -0.000000
5    AveOccup    -0.030602
6    Latitude    -0.790113
7   Longitude    -0.755674

In [15]:
print("Number of Features Removed:",
      np.sum(model.coef_ == 0))

Number of Features Removed: 1