In [60]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv('/home/mynk/Machine_learning_journey/Datasets/Churn_Modelling.xls')

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
df.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [32]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [34]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [35]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [77]:
print(df.columns.tolist())

['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_Germany', 'Geography_Spain', 'Gender_Male']

In [78]:
X = df.drop("Exited", axis=1)
y = df["Exited"].values

In [79]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [80]:
X = X.astype(int)

In [81]:
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0,1,1,1,101348,0,0,0
1,608,41,1,83807,1,0,1,112542,0,1,0
2,502,42,8,159660,3,1,0,113931,0,0,0
3,699,39,1,0,2,0,0,93826,0,0,0
4,850,43,2,125510,1,1,1,79084,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0,2,1,0,96270,0,0,1
9996,516,35,10,57369,1,1,1,101699,0,0,1
9997,709,36,7,0,1,0,1,42085,0,0,0
9998,772,42,3,75075,2,1,0,92888,1,0,1
9999,792,28,4,130142,1,1,0,38190,0,0,0

In [82]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state=42)

In [83]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [84]:
from tensorflow import keras
from tensorflow.keras import layers
from keras.layers import Dense, Flatten
from keras.models import Sequential

In [85]:
model = Sequential([
    Dense(32, activation='relu', input_dim=11),
    Dense(16,activation='relu'),
    Dense(1,activation='sigmoid')
])

model.summary()

/home/mynk/miniconda3/envs/ml/lib/python3.12/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 32)             │           384 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 929 (3.63 KB)

 Trainable params: 929 (3.63 KB)

 Non-trainable params: 0 (0.00 B)

In [86]:
model.compile(optimizer= 'adam', loss='binary_crossentropy', metrics=['accuracy'])

history = model.fit(X_train_trf,y_train,validation_split=0.2,epochs=100,batch_size=32)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7830 - loss: 0.4878 - val_accuracy: 0.8156 - val_loss: 0.4227
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8203 - loss: 0.4165 - val_accuracy: 0.8363 - val_loss: 0.3906
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8377 - loss: 0.3844 - val_accuracy: 0.8550 - val_loss: 0.3690
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.8487 - loss: 0.3638 - val_accuracy: 0.8569 - val_loss: 0.3600
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.8537 - loss: 0.3542 - val_accuracy: 0.8606 - val_loss: 0.3551
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8555 - loss: 0.3483 - val_accuracy: 0.8550 - val_loss: 0.3523
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8592 - loss: 0.3448 - val_accuracy: 0.8569 - val_loss: 0.3513
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8627 - loss: 0.3421 - val_accuracy: 0.8537 - val_loss: 0.3483
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8600 - loss: 0.3403 - val_accuracy: 0.8562 - val_loss: 0.3484
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8616 - loss: 0.3387 - val_accuracy: 0.8587 - val_loss: 0.3474
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8623 - loss: 0.3372 - val_accuracy: 0.8594 - val_loss: 0.3466
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.8627 - loss: 0.3348 - val_accuracy: 0.8581 - val_loss: 0.3466
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8608 - loss: 0.3342 - val_accuracy: 0.8569 - val_loss: 0.3479
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8622 - loss: 0.3326 - val_accuracy: 0.8550 - val_loss: 0.3436
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3302 - val_accuracy: 0.8562 - val_loss: 0.3448
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3296 - val_accuracy: 0.8556 - val_loss: 0.3435
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8625 - loss: 0.3286 - val_accuracy: 0.8575 - val_loss: 0.3427
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8648 - loss: 0.3282 - val_accuracy: 0.8569 - val_loss: 0.3413
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8652 - loss: 0.3274 - val_accuracy: 0.8569 - val_loss: 0.3418
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.8634 - loss: 0.3261 - val_accuracy: 0.8619 - val_loss: 0.3411
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.8678 - loss: 0.3252 - val_accuracy: 0.8594 - val_loss: 0.3403
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8628 - loss: 0.3256 - val_accuracy: 0.8600 - val_loss: 0.3407
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8637 - loss: 0.3241 - val_accuracy: 0.8587 - val_loss: 0.3415
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.8658 - loss: 0.3240 - val_accuracy: 0.8587 - val_loss: 0.3413
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8648 - loss: 0.3220 - val_accuracy: 0.8550 - val_loss: 0.3439
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8648 - loss: 0.3226 - val_accuracy: 0.8581 - val_loss: 0.3400
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8666 - loss: 0.3223 - val_accuracy: 0.8575 - val_loss: 0.3398
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.8670 - loss: 0.3209 - val_accuracy: 0.8600 - val_loss: 0.3394
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8683 - loss: 0.3196 - val_accuracy: 0.8562 - val_loss: 0.3419
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.8684 - loss: 0.3193 - val_accuracy: 0.8562 - val_loss: 0.3402
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.8700 - loss: 0.3197 - val_accuracy: 0.8612 - val_loss: 0.3418
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8695 - loss: 0.3186 - val_accuracy: 0.8569 - val_loss: 0.3389
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.8686 - loss: 0.3185 - val_accuracy: 0.8587 - val_loss: 0.3410
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.8691 - loss: 0.3174 - val_accuracy: 0.8606 - val_loss: 0.3396
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8680 - loss: 0.3169 - val_accuracy: 0.8556 - val_loss: 0.3427
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8689 - loss: 0.3164 - val_accuracy: 0.8581 - val_loss: 0.3393
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8698 - loss: 0.3166 - val_accuracy: 0.8594 - val_loss: 0.3419
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8706 - loss: 0.3150 - val_accuracy: 0.8569 - val_loss: 0.3407
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8680 - loss: 0.3148 - val_accuracy: 0.8606 - val_loss: 0.3430
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8694 - loss: 0.3153 - val_accuracy: 0.8575 - val_loss: 0.3399
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8708 - loss: 0.3137 - val_accuracy: 0.8581 - val_loss: 0.3404
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8698 - loss: 0.3139 - val_accuracy: 0.8544 - val_loss: 0.3426
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8686 - loss: 0.3128 - val_accuracy: 0.8569 - val_loss: 0.3397
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8700 - loss: 0.3124 - val_accuracy: 0.8587 - val_loss: 0.3412
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8675 - loss: 0.3124 - val_accuracy: 0.8550 - val_loss: 0.3408
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.8702 - loss: 0.3113 - val_accuracy: 0.8569 - val_loss: 0.3421
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.8737 - loss: 0.3096 - val_accuracy: 0.8569 - val_loss: 0.3418
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.8709 - loss: 0.3098 - val_accuracy: 0.8594 - val_loss: 0.3443
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.8689 - loss: 0.3100 - val_accuracy: 0.8562 - val_loss: 0.3415
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8719 - loss: 0.3093 - val_accuracy: 0.8569 - val_loss: 0.3427
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8712 - loss: 0.3087 - val_accuracy: 0.8587 - val_loss: 0.3412
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8705 - loss: 0.3082 - val_accuracy: 0.8612 - val_loss: 0.3445
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8736 - loss: 0.3083 - val_accuracy: 0.8594 - val_loss: 0.3423
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.8719 - loss: 0.3077 - val_accuracy: 0.8569 - val_loss: 0.3427
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.8720 - loss: 0.3074 - val_accuracy: 0.8556 - val_loss: 0.3430
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.8719 - loss: 0.3064 - val_accuracy: 0.8581 - val_loss: 0.3454
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.8714 - loss: 0.3057 - val_accuracy: 0.8631 - val_loss: 0.3441
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8736 - loss: 0.3054 - val_accuracy: 0.8600 - val_loss: 0.3453
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8745 - loss: 0.3039 - val_accuracy: 0.8606 - val_loss: 0.3484
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.8712 - loss: 0.3045 - val_accuracy: 0.8556 - val_loss: 0.3448
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.8742 - loss: 0.3030 - val_accuracy: 0.8544 - val_loss: 0.3433
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8728 - loss: 0.3027 - val_accuracy: 0.8550 - val_loss: 0.3440
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8742 - loss: 0.3040 - val_accuracy: 0.8587 - val_loss: 0.3467
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8736 - loss: 0.3023 - val_accuracy: 0.8600 - val_loss: 0.3472
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8731 - loss: 0.3023 - val_accuracy: 0.8550 - val_loss: 0.3463
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8752 - loss: 0.3010 - val_accuracy: 0.8544 - val_loss: 0.3524
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8761 - loss: 0.3004 - val_accuracy: 0.8612 - val_loss: 0.3513
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8747 - loss: 0.3000 - val_accuracy: 0.8600 - val_loss: 0.3433
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.8744 - loss: 0.3005 - val_accuracy: 0.8631 - val_loss: 0.3441
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.8769 - loss: 0.3003 - val_accuracy: 0.8569 - val_loss: 0.3486
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8772 - loss: 0.2994 - val_accuracy: 0.8606 - val_loss: 0.3472
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.8755 - loss: 0.2989 - val_accuracy: 0.8612 - val_loss: 0.3473
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8767 - loss: 0.2984 - val_accuracy: 0.8562 - val_loss: 0.3452
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8767 - loss: 0.2983 - val_accuracy: 0.8594 - val_loss: 0.3464
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.8775 - loss: 0.2975 - val_accuracy: 0.8537 - val_loss: 0.3478
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.8781 - loss: 0.2988 - val_accuracy: 0.8556 - val_loss: 0.3506
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.8763 - loss: 0.2970 - val_accuracy: 0.8575 - val_loss: 0.3460
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8767 - loss: 0.2979 - val_accuracy: 0.8594 - val_loss: 0.3471
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8791 - loss: 0.2961 - val_accuracy: 0.8575 - val_loss: 0.3485
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8789 - loss: 0.2961 - val_accuracy: 0.8544 - val_loss: 0.3520
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8763 - loss: 0.2959 - val_accuracy: 0.8562 - val_loss: 0.3523
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8777 - loss: 0.2948 - val_accuracy: 0.8550 - val_loss: 0.3529
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.8784 - loss: 0.2949 - val_accuracy: 0.8581 - val_loss: 0.3510
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8778 - loss: 0.2949 - val_accuracy: 0.8575 - val_loss: 0.3555
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.8766 - loss: 0.2951 - val_accuracy: 0.8569 - val_loss: 0.3529
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8788 - loss: 0.2939 - val_accuracy: 0.8575 - val_loss: 0.3524
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.8770 - loss: 0.2937 - val_accuracy: 0.8581 - val_loss: 0.3528
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8772 - loss: 0.2932 - val_accuracy: 0.8531 - val_loss: 0.3531
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8780 - loss: 0.2932 - val_accuracy: 0.8562 - val_loss: 0.3542
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.8794 - loss: 0.2923 - val_accuracy: 0.8587 - val_loss: 0.3512
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.8792 - loss: 0.2916 - val_accuracy: 0.8550 - val_loss: 0.3527
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8786 - loss: 0.2917 - val_accuracy: 0.8562 - val_loss: 0.3602
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8781 - loss: 0.2916 - val_accuracy: 0.8550 - val_loss: 0.3581
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8792 - loss: 0.2911 - val_accuracy: 0.8612 - val_loss: 0.3630
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8789 - loss: 0.2918 - val_accuracy: 0.8587 - val_loss: 0.3587
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8788 - loss: 0.2906 - val_accuracy: 0.8606 - val_loss: 0.3544
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8775 - loss: 0.2908 - val_accuracy: 0.8594 - val_loss: 0.3517
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8808 - loss: 0.2904 - val_accuracy: 0.8531 - val_loss: 0.3545
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8806 - loss: 0.2891 - val_accuracy: 0.8575 - val_loss: 0.3623
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8788 - loss: 0.2894 - val_accuracy: 0.8569 - val_loss: 0.3574

In [96]:
y_prob = model.predict(X_test_trf)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [97]:
y_pred = (y_prob > 0.5).astype(int)

In [98]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

0.853

In [101]:
model.evaluate(X_test_trf, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8530 - loss: 0.3671

[0.36705800890922546, 0.8529999852180481]

In [102]:
print(y_prob[:20])

[[0.01647048]
 [0.00470649]
 [0.0349789 ]
 [0.05575074]
 [0.18420093]
 [0.00180552]
 [0.22140816]
 [0.19487649]
 [0.33013806]
 [0.39815137]
 [0.99666977]
 [0.9753944 ]
 [0.84220594]
 [0.3861673 ]
 [0.02200344]
 [0.14421211]
 [0.09903757]
 [0.03550817]
 [0.02009369]
 [0.03750962]]